### ISSUE TITLE
D8 hub telemetry

### ISSUE THREAD

**Issue by LuckyFPV** [betaflight/betaflight-tx-lua-scripts#101]
I have a Beebrain V2 w/Frysky that uses D8 hub telemtry, I can see all the telemetry values on my X9 from the Flight controler but the bf.lua does not work. I have the most recent version and does work with other models.
Any help would be appreciated.

**Comment by mikeller** [comment]
No surprise there. FrSky hub / D8 does not support telemetry data transfer from the TX to the flight controller, so this can not work.

**Comment by LuckyFPV** [comment]
Thanks  How do they manage the stick commands via the OSD? That works fine. Infact I can see the same  menu options when i invoke the bf.lua that i see in the goggles with the sticks

**Comment by mikeller** [comment]
The stick commands are just read by interpreting the stick positions that are sent by RC commands. This has nothing to do with telemetry.
