### ISSUE TITLE
VTX screen out of memory

### ISSUE THREAD

**Issue by vandalum** [betaflight/betaflight-tx-lua-scripts#105]
When changing to the vtx screen it shows the following out of memory error:
script syntax error 
BF/ui.lua:335
not enough memory

This happens on a x9d plus with opentx 2.2.1-noheli connected to a bf 3.2.3 board and tbs unify race vtx with smart audio. Sometimes the screen shows the vtx settings but then the error pops up when trying to save new settings.

**Comment by raphaelcoeffic** [comment]
See #97
