### ISSUE TITLE
LED COLOR CHANGE - Feature request

### ISSUE THREAD

**Issue by Barux** [betaflight/betaflight-tx-lua-scripts#118]
Hi,
Would be great to have a .lua which allows to chang the led color,  is thre the possibility to find it in the near future?

From this year in the fai world cups and in others competitions, it s mandatory to have this feature.

Thank you

**Comment by kalosjann** [comment]
I was about to ask the same. Leds are becoming very requested in the competitions but also nice to see. Thanks to anybody will look into this point, I think the community will really appreciate that

**Comment by salem83** [comment]
Bump. Same here
