### ISSUE TITLE
Script not populating in d8 mode.

### ISSUE THREAD

**Issue by turboed13b** [betaflight/betaflight-tx-lua-scripts#122]
Everything works fine in d16 mode but there is a problem with my rx so I have to use d8 mode. Telemetry data shows up but script does not populate.

**Comment by codecae** [comment]
There's nothing specific about the script that could address this issue.  OpenTX supplies a generic function for pushing telemetry data to the FC.  If this does not work in D8 mode, there's nothing that can be done in the script to make it work, unfortunately.   I suggest reaching out to OpenTX regarding this issue.

**Comment by mikeller** [comment]
D8 (FrSky hub telemetry outside of OpenTX) is unidirectional and does not support sending of telemetry releated data from the TX to the flight controller, so this is a limitiation of the D8 protocol, and cannot be fixed.
