### ISSUE TITLE
Compatibility with TBS crosfire nano?

### ISSUE THREAD

**Issue by tronage** [betaflight/betaflight-tx-lua-scripts#123]
Scripts work perfect with my quads that have the micro receiver installed, but quads that have the nano version installed the script doesn't populate with values.  It doesn't report any error or anything, just the values are all "--" on all screens.  The two quads I have this running on are an HGLRX XJB 145 (Omnibus F4, running BF 3.3.0), and a newbeedrone beebrain v2 (running BF 3.3.1) just in case it is the FC that may present the issue, but figured it may be the rx since it is common between the two.  Let me know if this is known issue, or if I have to set something up different (vs the micro rx).  Let me know if you need any other info.

**Comment by codecae** [comment]
I've been running it with my nano on 3.3 for a while without issue.  Not sure it's hardware related.

**Comment by codecae** [comment]
Are you running both RX and TX wires to the nano?  Do you receive any battery or attitude telemetry?

**Comment by tronage** [comment]
I just checked and both nano's I have running, and I do not have battery or attitude telemetry.  And I do have both the tx and the rx wires connected in both builds: Nano pin1 (tx) to the rx on the fc, and Nano pin2 (rx) to the tx on the fc for the uart I'm using.  Both fly fine without issue, and hooked them up identically as I've done with the micro receivers (which all work perfectly).  I'm stumped, especially it being the case in two separate and unrelated builds that it doesn't work, while two builds using the micro (Holybro Kakute fc) work perfectly.  I'm running crossfire 2.24 firmware if that has anything to do with it (I think you need to be on 2.24 for the nanos anyway).  Maybe it is something simple I'm missing that is different with the nano?

**Comment by JonnyPhenomenon** [comment]
which uart do you have the nano connected to? when you run the crossfire lua on your taranis, do you see the RX?  are your channel assignments for it set up correctly?
can you switch one of your micro's into the place where your nano is connected? or switch your nano into a quad that has a micro in it? for testing I mean...

**Comment by JonnyPhenomenon** [comment]
ugh... I just hooked my nano up to my new betaflight f4 board, got it working right in the receivers tab, but I too have no telemetry on my taranis bf lua screens... I'm going to switch it over to my crossfire micro and test that right now...

**Comment by JonnyPhenomenon** [comment]
I hooked up my micro RX in place of the nano.  I don't get telemetry data on that one either in the bf lua. just a bunch of ---'s.  I am totally new to the whole telemetry, LUA, and crossfire game, so I have to assume I am doing something wrong...

**Comment by codecae** [comment]
Is telemetry enabled on the config tab?

**Comment by tronage** [comment]
OMG, I can't believe I missed that.  I knew if it wasn't a hardware issue, it would be something stupid.  That fixed it on my beebrain v2 board, the omnibus f4 board isn't handy right now to test, but I'm sure it will resolve it on that as well.  Thank you so much for the help!

**Comment by codecae** [comment]
Possibly unrelated, but something else to check.  I've learned among other conversations is that the little labels above the wire holes on the nano are actually ground.  Make sure that your wires are soldered only to the holes and that the wires don't extend over the holes onto these labels, as they can send the signal to ground.

**Comment by codecae** [comment]
I can say with 100% certainty that the nano rx works find for control and telemetry, so there must be something about your config that isn't quite right.  Can you take a picture of your nano rx settings in the crossfire script?

**Comment by mikeller** [comment]
@codecae: Re grounded labels: Ouch. But good observation, thanks.

**Comment by JonnyPhenomenon** [comment]
OK, spent entirely too much time on thi today when I should have been out flying, but I did figure out some things.
The flight controller I am using is th betaflight F4. I was trying to use UART2 for this, as the UART2 Rex and tax pads are in a convenient spot, and the 5v and ground pads right next to it are powered by the USB port when its connected to a PC.  Apparently, there is something up with the TX pad on this UART, because the crossfire tx can talk to the FC over it just fine, but the FC cannot send its telemetry data back to the transmitter over this uart.  When I soldered the crossfire rx over to uart 3 (and uart 1 as well) then everything worked fine.

The betaflight board source files mention that pin C13  provides inversion for UART2.  - somewhere else I saw a mention of the UART2 on bff4 board having inversion on both the rx and to of UART2, so this supposedly means it wont work... LAME!!!!

Why cant someone make “THE PERFECT BOARD” ???
*sigh*

**Comment by codecae** [comment]
Use uart4.  This is probably your issue.

**Comment by codecae** [comment]
Disregard, I deleted that comment.  Thought you were using a different board.

**Comment by codecae** [comment]
Try uart 1 or uart 3

**Comment by JonnyPhenomenon** [comment]
hah! yeah OK.  I Had wanted to use uart1 for the runcam split, then uart3 for tramp telemetry.  
the tramp only works on uart3 on this board, for whatever reason, although rumor has it that there is a uart6 TX pad on the bottom of the board which Does work for tramp as well.  I dont know if the split needs a whole uart, or just the TX. either way, uart 2 is a heap of sh1t and not usable for anything.

ho hum

at very least, I can finally attest that the crossfire micro, and crossfire Nano, BOTH work with this board, under BF 3.3.0, in CRSF mode, providing telemetry data to the taranis LUA script pages, as long as they are connected to either uart1 or uart3.  

it would be nice if someone who understands this a bit better than I do could take a look at it and see if there was some clever setting or mod or whatever that could be done to disable the inversion on uart2 TX to make it work with the crossfire, but until then, I will just have to deal with it as is.

**Comment by codecae** [comment]
Uarts 1 and 3 are likely your only options for crsf.

**Comment by codecae** [comment]
You could use soft serial for the tramp.

**Comment by codecae** [comment]
The TX6 pad on the bottom is also an option, but those tiny pads are quite fragile and the trace can easily be pulled from the board.

Given that this has been indicated as a wiring issue, I'll close this as an open issue with the scripts.  We can continue the dialog after closure if you'd like.

**Comment by JonnyPhenomenon** [comment]
Yup. The issue in my case is with the design of the board itself, on the specific UART (2). the uart 2 TX pad on the betaflight F4 is different from the others.  Which makes it unable to send data back to the crossfire RX.  This seems to be an issue for other f4 boards on specific UARTS.
