### ISSUE TITLE
How to get logical switch state from lua script?

### ISSUE THREAD

**Issue by BRoy98** [betaflight/betaflight-tx-lua-scripts#127]
Is it possible to get a **Logical Switch** state from lua script? 

I tried all these but value is always `0`
```
getvalue(LO1)
getvalue(lo1)
getvalue(L01)
getvalue(l01)
getvalue(l1)
getvalue(L1)
```

**Comment by raphaelcoeffic** [comment]
@BRoy98 could you please ask your questions related to the OpenTX LUA API in the OpenTX chatroom? It has nothing to do with this project.
