### ISSUE TITLE
Show deg/s in rates page

### ISSUE THREAD

**Issue by nmaggioni** [betaflight/betaflight-tx-lua-scripts#128]
It would be nice if the calculated _deg/s_ peak value of the curves could be reported in the first tab of the rates page.

Calculations used by the desktop configurator are reported [here](https://github.com/betaflight/betaflight-configurator/blob/24c81375a4da0e5ef6f7dda07d0674141a0cdc3b/src/js/RateCurve.js#L83).

**Comment by codecae** [comment]
I attempted to do this once before, but I don't believe we can pull all the values required his msp in a single request
