### ISSUE TITLE
Frsky X-lite not supported

### ISSUE THREAD

**Issue by jafc76** [betaflight/betaflight-tx-lua-scripts#134]
I just received the Frsky X-lite and after to install the LUA Scripts for Betaflight, I'm getting this error:

Script syntax error
BF/radios.lua:43
Radio not supported: xlit

I know that it's a new radio so waiting for the compatibility with it.

Thanks in advance.

**Comment by raphaelcoeffic** [comment]
@jafc76 there are certain unknowns as-of the available navigation keys inside the script (being sorted out in OTX dev chat right now). Once this is done, I might make the necessary adjustments.

**Comment by raphaelcoeffic** [comment]
@jafc76 could you please test the code changes I've just made? Please bare with me, I have no way to test anything...

**Comment by jafc76** [comment]
raphaelcoeffic, Thank you very much!!! It works!!!

The small joystic is working like this. If I move the joystick to the right, the cursor is moving down to the next option inside of that screen, if I move to the left, the same but going up inside of the same screen.
If I move the joystick up, I go to the next page, from PID screen, to rates1, rates2, etc... but if I move the joystick down to go to the previous page, doesn't go back.


Anyway, at the moment, it works, maybe a little tricky how the joystick works but it's functional. Thank you very much again!!

**Comment by raphaelcoeffic** [comment]
Can you please confirm if you can reach the menu (long-UP)?
“Previous page” with the down key can be done easily.

**Comment by jafc76** [comment]
To go to the LUA screen I have to press a long-down.

Inside of the LUA screen if I make a long-up I get one screen with this message:

Menu: save page
             reload
             reboot

**Comment by raphaelcoeffic** [comment]
@jafc76 glad to hear it works properly!

**Comment by raphaelcoeffic** [comment]
@jafc76 I made a small modification to support "previous page". The keys have been slightly changed to fit that logic:
- next page: DOWN
- previous page: UP
- pop-up menu: long DOWN

Would you mind re-testing?

**Comment by jafc76** [comment]
I just copied the files to test it and works like a charm!

long-down to go to the LUA script.

right to go down and left to go up inside of each screen.

down to go to the next page and up to the previous one.

long down pop-up menu

Don't worry about to test it, I really appreciate your time and work!!

Eveything is good now, but if you change to move down pressing down, up pressing up, next page pressing right, previous pressing left, will be perfect!! Only if you can, no pressure.

Thanks again!!!

**Comment by raphaelcoeffic** [comment]
Ah ok! So basically switching both axis? No problem ;-)

**Comment by jafc76** [comment]
Yes! I think will be more intuitive to navigate through the menu. You are the man! :)

**Comment by jafc76** [comment]
Working!! It's perfect in my opinión.

The only think I don't like is the pop-up menu. Will be better cleaning the background but anyway at the moment is just fine!!

![photo_2018-05-27_02-27-29](https://user-images.githubusercontent.com/4662811/40581331-eb4550b0-6155-11e8-9085-e4e4400948dd.jpg)

Thank you so much!

**Comment by raphaelcoeffic** [comment]
I believe that one is an issue with OpenTX itself, as it works on X7 correctly. I’ll deal with it ;-)

**Comment by raphaelcoeffic** [comment]
https://github.com/opentx/opentx/issues/5912

**Comment by jafc76** [comment]
Working! Thank you very much!
![b23bb8b8-95b6-41b0-8db0-01625decd110](https://user-images.githubusercontent.com/4662811/40592656-f0bca09a-625c-11e8-9ed8-05bbaaef862e.jpeg)

**Comment by ps915** [comment]
I tested the latest LUA Script with OpenTX **2.2.2 RC2**.

Navigation is just fine but the **"save page"** dialog is on **"long right"** button.

Wouldn't it be better (more intuitive) to use the **"Function/Shift Button"** to get to the menu?

Here is a video, how we set the buttons for KISS LUA Script: 

https://www.youtube.com/watch?v=ksF3GtHy5KU

[![LUA Script X-Lite KISS CC - Test #04](https://img.youtube.com/vi/ksF3GtHy5KU/0.jpg)](https://www.youtube.com/watch?v=ksF3GtHy5KU)

**Comment by DieHertz** [comment]
Honestly I would prefer Enter to be long click on joystick as well, I'll look into it

**Comment by ps915** [comment]
Yes, that would be also my Nr 1 but if you hit Enter long you get "telemetry reset" and thats not LUA Script related programming, its OpenTX, right?
