### ISSUE TITLE
Antigravity increment problem

### ISSUE THREAD

**Issue by rnelias** [betaflight/betaflight-tx-lua-scripts#136]
Problem description:

when trying to increment/decrement Antigravity value, it uses 1.0 as increment instead of 0.1

**Comment by raphaelcoeffic** [comment]
@rnelias which page / TX?

**Comment by rnelias** [comment]
after struggling with github, just saw what you've made and changed locally on my rates2.lua files.

Just tried and it's working fine :)

**Comment by raphaelcoeffic** [comment]
Cool! Nice to hear that!

**Comment by raphaelcoeffic** [comment]
Implemented by #137
