### ISSUE TITLE
FrSky Taranis X-Lite support

### ISSUE THREAD

**Issue by ps915** [betaflight/betaflight-tx-lua-scripts#142]
Can we add the FrSky Taranis X-Lite. Should be the QX7 Script with changed Button resources?
I can help testing it! ;)

**Comment by DieHertz** [comment]
Philip, I told you in private on Facebook twice that Xlite is already supported, use X7 Lua.

**Comment by DieHertz** [comment]
Solved by #135

**Comment by ps915** [comment]
oh damn, i just copied the wrong files! my bad! Sorry! It works!
