### ISSUE TITLE
BF3.4RC2, Lua 1.0.2: Motors page not showing any values...

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-tx-lua-scripts#143]
referencing to BF #6210 https://github.com/betaflight/betaflight/issues/6210

**Comment by codecae** [comment]
Is this still an issue with 3.4 stable?

**Comment by RipperDrone** [comment]
Yep, I'm on 3.4 stable

**Comment by simogere** [comment]
Any news?

**Comment by mikeller** [comment]
@simogere: This is for 3.4. We're on 3.5 now, so you should probably test with 3.5.

**Comment by simogere** [comment]
Tested with 3.4.1 and 3.5. Same issue: no values. My rx is a Frsky R9 mini. Radio is a Qx 7. All the stuff is updated.

**Comment by simogere** [comment]
Any tip?

**Comment by simogere** [comment]
Come on, please...

**Comment by mikeller** [comment]
@simogere: Being pushy will not improve the chances of anybody being keen to answer / help you...
