### ISSUE TITLE
Fport telemetry and lua not working

### ISSUE THREAD

**Issue by thankneptune** [betaflight/betaflight-tx-lua-scripts#144]
I have fport setup on a frsky r-xsr rx, betaflight 3.4 on my fc, and latest firmware on the rx. Rx is bound, betaflight sees inputs from tx. Uninverted s.port wire connected to uninverted tx3.
However, on my tx, telemetry only shows rssi and rx voltage, no other sensors, and lua scripts won't display any information at all.

tx - Taranis QX7
rx - r-xsr (fport, firmware 180228)
fc - DYS F4 pro omnibus
betaflight 3.4
non-eu for everything if that matters.

**Comment by raphaelcoeffic** [comment]
The script is based on telemetry, so please, first make it work, then the script should be ok.

**Comment by mikeller** [comment]
@thankneptune: Are you sure you are connected to TX3 on the flight controller, and not RX3? What you describe (input from TX, but no telemetry) sounds like you are connected to RX3. If not, try rediscovering the sensors.
