### ISSUE TITLE
Dsetweight not working  on LUA Betaflight 3.4

### ISSUE THREAD

**Issue by DroidmanFPV** [betaflight/betaflight-tx-lua-scripts#146]
I did the update to Betaflight 3.4 and the dsetweight setting do not save. I'm using crossfire, Revolt V3 board.

**Comment by mikeller** [comment]
@DroidmanFPV: What version of the lua scripts are you using?

**Comment by DroidmanFPV** [comment]
I'm using the latest Lua Script Version. I tried to use with a CLRacing F4 V2 with Crossfire as well and had the same problem. The Gyro filter option do not save and the Dsetweight do not save. Thanks!

**Comment by DroidmanFPV** [comment]
OpenTX 2.2.1

**Comment by codecae** [comment]
We corrected this, I believe..hmm

**Comment by codecae** [comment]
Taking a look now.

**Comment by codecae** [comment]
Please give this a try:

[bf-tx-lua-dsetpointfix.zip](https://github.com/betaflight/betaflight-tx-lua-scripts/files/2194412/bf-tx-lua-dsetpointfix.zip)
