### ISSUE TITLE
Impossible to scroll through the page on X7

### ISSUE THREAD

**Issue by Bozbi** [betaflight/betaflight-tx-lua-scripts#15]
I have the bf lua script installed on x7. I can read the values when i power on my quad. but i can't scroll up and down with the "wheel". it's like the wheel is not working in the script page. i have last open tx nb and last bf lua script.
Thanks for your help

**Comment by JR63** [comment]
This is an openTX issue that will be fixed in RC11.
Till then start the script directly and not via telemetry screen.
