### ISSUE TITLE
Minor textual improvement

### ISSUE THREAD

**Issue by 0crap** [betaflight/betaflight-tx-lua-scripts#165]
Is it possible to change, in the Betaflight / Rates (3/3) page, the text Anti-Grav Thr to Anti-Grav Thr**e** ?
Thr is often referred to as Throttle.
Adding only an e makes it much more clear it's about Threshold.

Just a small suggestion. Thx!

**Comment by 0crap** [comment]
![20180829_191213](https://user-images.githubusercontent.com/31951195/44804420-90bad000-abc1-11e8-9da1-0afc2e4b0bac.jpg)

**Comment by klutvott123** [comment]
Good suggestion. I would have changed it to "thld" which is commonly used in aviation according to https://www.allacronyms.com/threshold/abbreviated

**Comment by 0crap** [comment]
No need to play it by the aviation book. ;-)

Coming from rc helicopters, in my mind that is Throttle Hold.
Oh well.....

**Comment by mikeller** [comment]
I like this one: https://www.allacronyms.com/THRSH/Threshold

Nine out of ten pilots will read this as 'trash'...

**Comment by 0crap** [comment]
trash..., yes indeed. :-)

**Thrsh** is perfect, lets give that a go.

**Comment by ijustwannafly** [comment]
rates3.lua

{ t = "Anti-Grav Thrsh",  x = 15, y = 30, to = SMLSIZE },

You can add the edit now or grab the latest build from the jenkins website.

**Comment by 0crap** [comment]
Thx! Tested and works great.
Can you please make a Pull request so it will end up in the official code?

Much appreciated.

**Comment by 0crap** [comment]
No stale bot please.
Still hope this can be done.

**Comment by 0crap** [comment]
Merged, so can be closed.
Thx all. 👍
