### ISSUE TITLE
Xlite crossfire Lua

### ISSUE THREAD

**Issue by viperfpv** [betaflight/betaflight-tx-lua-scripts#171]
Will there be support to get the crossfire lua to work with the xlite? I just watched a video and it showed the crossfire script but when you click it nothing happens.

**Comment by alex-vg** [comment]
Wrong repo, this is for BF lua. https://github.com/opentx/opentx/pull/5985

**Comment by mikeller** [comment]
@viperfpv: These scripts should work on the X-lite with SmartPort / FPort or with crossfire.

There are also scripts that use CMS over crossfire that you could try:
https://github.com/betaflight/betaflight-crsf-tx-scripts
