### ISSUE TITLE
Feed Foward and I-term

### ISSUE THREAD

**Issue by wascheck** [betaflight/betaflight-tx-lua-scripts#173]
Radio: QX7
OPENTX: 2.2.2
Lua Script V 1.0.2 updated today
Betaflight 3.5.1
Holybro kakute f3
I've updated the lua script but doesn't show the feed foward neither the Iterm.
Any suggestion?

**Comment by mikeller** [comment]
@wascheck: We have not yet done a release of the lua scripts to go with 3.5, but it is planned to do one within the next few days. Watch this space!

**Comment by wascheck** [comment]
Thanks a lot for answering! Gona be watching.

Em 9h31 Ter, 25/09/2018, Michael Keller <notifications@github.com> escreveu:
