### ISSUE TITLE
Xlite not Supported?

### ISSUE THREAD

**Issue by bokie1** [betaflight/betaflight-tx-lua-scripts#178]
Tx: Frsky X-Lite
Opentx Version: 2.2.2 and also tested on 2.2.3N682
Issue: When choosing BF lua on telemetry screen it gives out an Error message:
       Script syntax Error - Telemetry protocol not supported

Comparison: Inav and yaapu (for Ardupilot) lua scripts work without issues.

**Comment by mikeller** [comment]
Have you tried running 'Discover new sensors', and then tried again?
