### ISSUE TITLE
Display Distance, Speed, Mode, Battery etc

### ISSUE THREAD

**Issue by henfri** [betaflight/betaflight-tx-lua-scripts#182]
Hello,

as far as I understand, these scripts can influence the PID values and the VTX settings.
But I think they cannot display Information like Battery status, Flight Mode etc., right?

Would you consider adding this as a Feature?
I am thinking of something like this:
https://uploads.tapatalk-cdn.com/20170215/9fcc412dddc41fc54b59281c21790afe.jpg

Greetings,
Hendrik

**Comment by mikeller** [comment]
I think it is preferable to keep configuration and live data display in separate applications. Or what benefit do you see in combining them into one script?

**Comment by henfri** [comment]
Hello,

I assumed synergies, but you can judge better.
How do you currently display the telemetry, by the way?

Regards,
Hendrik

**Comment by mikeller** [comment]
@henfri: There aren't that many synergies, as the configuration script uses MSP over SmartPort to get / set data, and the telemetry script will be using telemetry data (available on FrSkyHub and SmartPort, and for firmwares that are not Betaflight) to get read only telemetry data.

**Comment by henfri** [comment]
ok, thanks.

Out of curiosity: How are you displaying the telemetry? 
Some of the data (e.g. Flight mode) is encoded so that it is machine, but not human readable...
Greetings,
Hendrik

**Comment by mikeller** [comment]
@henfri: I just use the telemetry displays built into OpenTX - telemetry is only secondary to me, as I am not looking much at my TX while flying.
