### ISSUE TITLE
Smart Audio Bug

### ISSUE THREAD

**Issue by Jahnkeanater** [betaflight/betaflight-tx-lua-scripts#184]
Just updated to lua v1.1.0 on my X-lite running open tx 2.2.2
Smart audio works but certain channels will not save. I can tune to channels 1 and 4 etc. But channels 2 and 3 will not save. The power level settings seem to save fine. Using the OSD menu seems to work fine.

**Comment by mikeller** [comment]
@Jahnkeanater: What firmware version are you using on your RX? There's a nasty bug in many RX firmware versions (#151) that prevents certain values from being sent between the lua script and the firmware. This could be another incarnation of this bug.
