### ISSUE TITLE
TRAMP protocol and SMARTPORT fail to set specific settings

### ISSUE THREAD

**Issue by hsuq510** [betaflight/betaflight-tx-lua-scripts#186]
I got a TRAMP with smartport connected on the telemetry PAD, script works however with some specific combination it fails (2 times) to save values.

Example if I have R1 I cannot set 200mW, just 25, 100, 400
If I move to F1 I can set 200mW, however If I try to switch back to R1 it fails. 

It seems some combo just fails. However if I set R1 and power 200mW from CLI it works, so I assume its a script issue.

Ive got the latest version of the LUA, OpenTX 2.2.2, beta 3.5.3

**Comment by mikeller** [comment]
Could be another instance of #151 (i.e. some specific values won't transfer over SmartPort). Have you tried updating your RX firmware to any of the fixed versions posted in #151?

**Comment by hsuq510** [comment]
RXSR_FCC180921_Beta.frk.zip for smartport found in #151 fix the issue.

@mikeller Thanks for your reply.
