### ISSUE TITLE
LUA script kicks me out + BF lua does not show telemetry

### ISSUE THREAD

**Issue by OxygenGS** [betaflight/betaflight-tx-lua-scripts#198]
Hello,

I got crossifre since yesterday.
I got  a micromodule with version 2.88, and the new Nano diversity receiver and it did bind and update. It also flys amazing, rssi 99! However, i see 2 issues here and cannot fix it.
I use the XQ7 so i did apply the mod with the chip that came with it, also easy. The issues i have are:
1: If i go (like you see in the video) to system -> crossife -> Crossfire lua and execute -> then select the nano diversity receiver -> it opens up but if i go down or even stay idle in it, it just kicks me out and i need to re-open and execute the script. I get no change to change stuff in there, did manage to get rx and tx and the rssi setting in channel 12, but with ALLOT of retrys and this is not how it should work right?
2: Normaly with my X4R i did hold page in the main screen to get the PID and stuff via de BF lua. Now however if i open it, it does not show me any valleus, how to fix this pls? this is a big issue out on the field when i wanna tune my quad and chnage settings.

I hope you guys have a fix for me for these 2 issues.d

Greets

[Video.zip](https://github.com/betaflight/betaflight-tx-lua-scripts/files/2870780/Video.zip)

**Comment by BradB111** [comment]
> Hello,
> 
> I got crossifre since yesterday.
> I got a micromodule with version 2.88, and the new Nano diversity receiver and it did bind and update. It also flys amazing, rssi 99! However, i see 2 issues here and cannot fix it.
> I use the XQ7 so i did apply the mod with the chip that came with it, also easy. The issues i have are:
> 1: If i go (like you see in the video) to system -> crossife -> Crossfire lua and execute -> then select the nano diversity receiver -> it opens up but if i go down or even stay idle in it, it just kicks me out and i need to re-open and execute the script. I get no change to change stuff in there, did manage to get rx and tx and the rssi setting in channel 12, but with ALLOT of retrys and this is not how it should work right?
> 2: Normaly with my X4R i did hold page in the main screen to get the PID and stuff via de BF lua. Now however if i open it, it does not show me any valleus, how to fix this pls? this is a big issue out on the field when i wanna tune my quad and chnage settings.
> 
> I hope you guys have a fix for me for these 2 issues.d
> 
> Greets
> 
> [Video.zip](https://github.com/betaflight/betaflight-tx-lua-scripts/files/2870780/Video.zip)

Did you ever get anywhere with this? my bf lua scripts come up blank too but telemetry works, all my other RXs are fine (normal crossfire nanos and R-XSRs) Just my Crossfire nano diversity.
