### ISSUE TITLE
GPS Rescue layout mix-up

### ISSUE THREAD

**Issue by Jetrell** [betaflight/betaflight-tx-lua-scripts#215]
Presently -
`Ground speed` is displayed under `Throttle Minimum` on the script.
`Hover Throttle`  is displayed under `Ground speed` on the script.
`Throttle Minimum `is displayed under `Hover throttle` on the script.

![Capture](https://user-images.githubusercontent.com/47995726/56784793-aa3a1780-6835-11e9-9703-1de01036c6a9.PNG)
![20190426_145907](https://user-images.githubusercontent.com/47995726/56784795-ab6b4480-6835-11e9-9949-82fa26885c54.jpg)

Are these figures just in the wrong location and GPS rescue can still be tuned from the script?

**Comment by klutvott123** [comment]
@Jetrell You're right. Those parameters were mixed up for the X9. They can still be tuned from the script. Just have to be aware that they are mixed up.  Fixed in #216. Try it out if you want and thanks for letting us know! 👍

**Comment by Jetrell** [comment]
Thank you for the fix.  I'll give it a go once its merged to the master.
