### ISSUE TITLE
Great but missing some features 

### ISSUE THREAD

**Issue by Dutchy-79** [betaflight/betaflight-tx-lua-scripts#22]
This is really great. 

Only thing is I miss the option to show profile 1 2 and 3.

And when switching to another profile with the sticks the page isn't updated, you need to change page and back to update it. 

I'd like to see it showing the selected profile and update the numbers when changing profile. 

Regards,

**Comment by beeb** [comment]
Additionnally, I think it would be nice, if technically feasible, to be able to switch between rate profiles (on top of pid profiles). Cheers

**Comment by mikeller** [comment]
@beeb: Just in case you are not aware: It's possible to configure rate profile switching onto a 3 position switch through the 'Adjustments' tab, and then switch in-flight.

**Comment by beeb** [comment]
@mikeller absolutely! The only problem is that I have no free channel on my RX for this (all occupied by flight mode, buzzer, reverse dshot direction and arm switch). I could re-bind my RX with 16 channels but I heard it increases the latency slightly over 8 channels.

**Comment by mikeller** [comment]
@beeb: There are plans to address this shortcoming in 3.3. Watch this space. ;-)
