### ISSUE TITLE
X9 Lite support

### ISSUE THREAD

**Issue by czuryk** [betaflight/betaflight-tx-lua-scripts#223]
Need adding X9 Lite support.
It can be fixed by adding following string in radios.lua
["x9lite"] = supportedPlatforms.x7

**Comment by mikeller** [comment]
@czuryk: Can you please open a pull request for this change? Thanks.

**Comment by klutvott123** [comment]
It was added in #220
https://github.com/betaflight/betaflight-tx-lua-scripts/blob/1417c399941983bb15ffb02858db620a6f066dd7/src/SCRIPTS/BF/radios.lua#L35

**Comment by mikeller** [comment]
Sorry @klutvott123, I've kind of lost track in the flurry of hardware that FrSky is releasing. :stuck_out_tongue_closed_eyes:

**Comment by klutvott123** [comment]
@mikeller So many s, lites and pros lol

**Comment by mikeller** [comment]
@czuryk: Looks like it's already supported - can you close this please?

**Comment by czuryk** [comment]
> 
> 
> @czuryk: Looks like it's already supported - can you close this please?

I am sorry but I still dont see release with with issue....
https://github.com/betaflight/betaflight-tx-lua-scripts/releases

**Comment by mikeller** [comment]
@czuryk: There you go: https://github.com/betaflight/betaflight-tx-lua-scripts/releases/tag/1.3.0

**Comment by czuryk** [comment]
Excellent!
Thanks!
