### ISSUE TITLE
When connected to open tx I get  "Firmware update check failed" new version info not found or invalid

### ISSUE THREAD

**Issue by itsmerandy** [betaflight/betaflight-tx-lua-scripts#224]
Hello, Purchased a new Taranis X-Lite and went through process of upgrading the firmware and had issues with OpenTx giving me error messages everytime I open it with controller connected. nIt doesn't matter if controller is in Bootloader mode or turned off or on I still get this message.
"Firmware update check failed, New version information not found or invalid."  
Also I get an SDcard error on x-lite when I turn it on  "Expected version: 2.2V0016"  The Sdcard has a newer SDCard version 2.3V0019 on it, why is it expecting an older SDcard ver?
Sorry, I'm really new to all of this. Thanks

**Comment by mikeller** [comment]
@itsmerandy: This is the Betaflight project's issue tracker - we do not do anything with the firmware on your TX. https://github.com/opentx/opentx is the right place to open an issue for your problem.

**Comment by itsmerandy** [comment]
Sorry.  Can I just copy and paste it over there?

**Comment by mikeller** [comment]
@itsmerandy: Knock yourself out.
