### ISSUE TITLE
arrow keys on taranis x-lite

### ISSUE THREAD

**Issue by wildflyer** [betaflight/betaflight-tx-lua-scripts#226]
would it be possible to add to left-right arrow keys to edit the parameters? at the moment you can change a value only with up-down arrow keys. left right and up-down would be perfect.

**Comment by Matze-Jung** [comment]
Hey wildflyer,

I don't think thats an easy task. Guess it would colide with the page scrolldown feature. 
If you want customizable controls, you might check out my [mod fork I just launched](https://github.com/Matze-Jung/betaflight-tx-lua-scripts-mod).

**Comment by wildflyer** [comment]
I dont think it collides with the scrolldown, because it would be only when a value is edited.
