### ISSUE TITLE
Menu button on Taranis X7 does not work running OpenTX 2.3

### ISSUE THREAD

**Issue by vkolotov** [betaflight/betaflight-tx-lua-scripts#227]
I'm testing OpenTX 2.3 and lua scripts (latest release - 1.3.0). I can switch to a display with lua script and I can see my PIDs, however I cannot switch to other screens or save changes. Effectively "menu" button does not work, when I push it (either long or short) nothing happens.

Is there any way to debug this issue?

**Comment by mikeller** [comment]
As far as I can tell there is no 'OpenTX 2.3' release - is it possible that this is just a bug in a development build? You should probably report this as an issue against OpenTX.

**Comment by klutvott123** [comment]
https://github.com/opentx/opentx/pull/6502 maybe. Looks like they're in the process of implementing "virtual keys" for LUA. Probably still work in progress.

**Comment by vkolotov** [comment]
Thanks guys, I'll close it.

**Comment by vkolotov** [comment]
Just for a reference: https://github.com/opentx/opentx/issues/6509
