### ISSUE TITLE
don't work with matek f722-mini

### ISSUE THREAD

**Issue by wsnzone** [betaflight/betaflight-tx-lua-scripts#233]
opentx 2.2.3 + lua 1.3.0
matek f722-mini + tbs diversity nano, bf 4.0.4

**Comment by klutvott123** [comment]
It's a tbs diversity nano firmware issue. Read towards the end here https://github.com/betaflight/betaflight-tx-lua-scripts/issues/185. The solution is to use the latest beta firmware for the receiver.
