### ISSUE TITLE
X9D+2019 Radio Not Supported

### ISSUE THREAD

**Issue by twidgit** [betaflight/betaflight-tx-lua-scripts#238]
Request support for the 2019 (ACCESS) edition of the X9D+.

Attempted to run script on Betaflight 4.0.5, script version 1.3, OpenTX 2.3N69.

**Comment by mikeller** [comment]
@twidgit: The scripts are only targeting stable versions of OpenTX - use 2.2.4.

**Comment by mikeller** [comment]
Getting support for your hardware added to a stable version of OpenTX is something you'll have to raise on https://github.com/opentx/opentx/issues and not here.

**Comment by mikeller** [comment]
That's something we can do once it is confirmed that this is how the radio will be called in a stable version of OpenTX - there is no point doing this now, as there does not seem to be a released version of OpenTX that runs on your radio.

**Comment by raphaelcoeffic** [comment]
@mikeller I don’t think the radio string will change until 2.3 release. It is probably worth adding to the scripts. The changes are probably minimal.

**Comment by mikeller** [comment]
@twidgit: Please read https://github.com/betaflight/betaflight-tx-lua-scripts/issues/238#issuecomment-525536988. This is not a matter of supporting a particular hardware type, this is a matter of supporting only released versions of OpenTX.
