### ISSUE TITLE
script syntax error setrtc time (nil value..

### ISSUE THREAD

**Issue by JR555SE** [betaflight/betaflight-tx-lua-scripts#241]
Hi!

getting 
------------------
script syntax error 
?:0
attempt to call field 'getRtcTime' (a nil valu..
--------------------------
I am missing something obvious here I think. I downloaded lua version 1.30 and started getting these as soon as I try to launch the lua script(through telemetry page)
so I downgraded and found its all starting with bf4.0 version of lua.
lua as such works if I open the script before turning on the quad but not if its started while quad is running and telemetry is working.
 
I have the opentx 2.2.1 and taranis x9d running crossfire
What have I missed?
Tried searching for this or similar error but couldn't find any other reporting this :/

Best regards
Johan

**Comment by mikeller** [comment]
@JR555SE:

> What have I missed?

OpenTX 2.2.2 (or better) is what you have missed - `getRtcTime()` was only added in OpenTX 2.2.2. Update OpenTX and you'll be fine.

**Comment by JR555SE** [comment]
Thank you!!
