### ISSUE TITLE
Lua Script Taranis X9D+ Plus 2019 

### ISSUE THREAD

**Issue by wascheck** [betaflight/betaflight-tx-lua-scripts#247]
I received this radio today and tried to install the lua script v1.3.0  and it did not worked.
The message :
Script Syntax error
BF/radios.lua:47
Radio not supported: X9D+2019

**Comment by raphaelcoeffic** [comment]
The code has already been added, but not yet included in a release. Sorry for that, but you’ll have to wait a bit.

**Comment by wascheck** [comment]
Ok....thanks a lot for the answer. Gona be waiting the new version with it
fixed.

Em sex, 4 de out de 2019 20:40, Raphael Coeffic <notifications@github.com>
escreveu:

**Comment by AndyJack0764** [comment]
Hi, similar issue here with X9D+2019,   would the older version work meantime?
tks

**Comment by wascheck** [comment]
Works perfectly with my QX7 with Opentx V2.3.....

Em sáb, 5 de out de 2019 09:10, AndyJack0764 <notifications@github.com>
escreveu:

**Comment by Hillgoonfpv** [comment]
Is there an ETA as to the release for this?

**Comment by raphaelcoeffic** [comment]
@Hillgoonfpv whenever there is a next release, which should happen in short.

**Comment by raphaelcoeffic** [comment]
@Hillgoonfpv 1.4.0 provides support for the X9D+ 2019. Please re-test directly with the ZIP file in #260, as it contains some fixes.
