### ISSUE TITLE
VTX power

### ISSUE THREAD

**Issue by plemnik166** [betaflight/betaflight-tx-lua-scripts#249]
Hi, I'm new here.
I have a question
Can I change Power smart audio in the lua script in the vtx file from 25, 200, 500, 800 to tbs compatible with uni32 pro32 hv, i.e. 25, 100, 400, 1000.? will this work?

**Comment by mikeller** [comment]
@plemnik166: GitHub is for questions and discussions around **development** of Betaflight. Please use RCGroups or the Betaflight Facebook group for questions about configuration and use.
