### ISSUE TITLE
X9D+ - virtual events lua still not correct

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-tx-lua-scripts#255]
@raphaelcoeffic @mikeller sry to report non-working fix for Lua - PIDs adjustment.

To replicate:
- flash OTX 2.3.1 onto Taranis X9D+
- flash latest / toay's Nightly OMNINXTF7 FW with BFC 10.6.0RC2
- load latest today's lua onto Taranis (delete all .luac files on Taranis, let them recompile automatically by Taranis when switching on) from repository's /src directory
- long press PAGE to get into telemetry page, short press to get on PID manipulation page
- edit first field, press '-' --> Field value decrements ok
- press 'ENTER' --> field value jumps back to old value

Same thing happens when incrementing the value first, it then jumps back down again.

Funnily, in repeating this procedure, 2nd time trying to change the same value, it retains the change.

@mikeller you reported the script working ok. Any difference btw your test sequence and mine?

**Comment by mikeller** [comment]
Thanks @RipperDrone. I just verified again, and it's working fine on X9D+ with 2.3.0 - looks like they've broken it in the changes for 2.3.1. :frowning_face:

**Comment by raphaelcoeffic** [comment]
Really strange, it’s working fine in the Simu in 2.3.1. @RipperDrone did you try with the code from the other PR?

**Comment by robschii** [comment]
in als menus of the lua script    als values jump back to the value before...  i will stay at opentx 2.2.4

**Comment by RipperDrone** [comment]
@raphaelcoeffic pls specify 'other PR' a little more. I have tested with y'day's .zip download of master, so both PRs should have been included in the /src directory, shouldn't they?

**Comment by raphaelcoeffic** [comment]
@RipperDrone sorry, I meant #250. Please note that the ZIP file is outdated. Just use the files in `src/`.

**Comment by RipperDrone** [comment]
Success! Working now that I downloaded the /src files from the correct branch. Thank you @raphaelcoeffic - and closing this issue accordingly.

Now we have to handle the 'background noise' from people NOT matching the correct versions of lua and OTX - hope there is a consistent way out :-)
