### ISSUE TITLE
Taranis x-lite joystick not operating normally: lua 1.4

### ISSUE THREAD

**Issue by mdibe** [betaflight/betaflight-tx-lua-scripts#261]
On lua 1.4 when using the joystick of the x-lite radio for moving among the pages:

joystick right and left -> move inside the page
joystick down -> go to next page
joystick up -> also go to next page
there is no possibility to go backward but keep moving forward until completing the loop

Am I the only one having this trouble?
Would it be more normal to change it in this way?

joystick right -> go to next page
joystick left -> go to previous page
Joystick up and down -> move inside the page

**Comment by raphaelcoeffic** [comment]
This is mainly dependent on the events generated by OpenTx. The navigation will be rotated by 90° in next minor release (2.3.2). Are you actually executing the script from the telemetry pages or as a standalone script? This changes which logical key is responsible for paging ("next page" vs "menu"). Please note that the current navigation is now consistent with what you have in the rest of the OpenTX navigation.


Please have a look at this PR: opentx/opentx#6916.
You should also test the fixes for 1.4.0 located in #260.

**Comment by mdibe** [comment]
I see, #6916 seems will solve the issue in 2.3.2 release.

I tested lua 1.4.1 and there is a difference if the script is executed as standalone or via the telemetry page:

Telemetry page:
joystick right and left -> move inside the page
joystick down -> go to next page
joystick up -> no behavior

as Standalone (opening it from the sd card):
joystick right and left -> move inside the page
joystick down -> no behavior
joystick up -> go to next page

**Comment by raphaelcoeffic** [comment]
@mdibe thx, that‘s expected.
