### ISSUE TITLE
X9 Lite support

### ISSUE THREAD

**Issue by alexdibi** [betaflight/betaflight-tx-lua-scripts#271]
version 1.4.1 don't support x9 lite

**Comment by mikeller** [comment]
@alexdibi: Can you please supply a little bit more information like what exactly is not working, or what error message you are getting?

**Comment by alexdibi** [comment]
I get error: 
Script Syntax Error
BF/radios.lua 
incompatibile precompiled

**Comment by mikeller** [comment]
@alexdibi: And what version of OpenTX are you running?

**Comment by alexdibi** [comment]
2.3.1

**Comment by mikeller** [comment]
Interesting. I don't see why this would not work. When did you download the scripts?

**Comment by alexdibi** [comment]
Yesterday... i tried inserting the string ["x9lite"] = supportedPlatforms.x7
in radios.lua and the First Page work than on second Page i give an Error in functions.lua

**Comment by mikeller** [comment]
@alexdibi: If you want to run your own modified version of scripts you are on your own. If you want to ask for support here try running the released version.

**Comment by alexdibi** [comment]
i have tried now i'm on 1.3.0

**Comment by alexdibi** [comment]
1.4.1 official don't work on x9 lite

**Comment by frozenskys** [comment]
What error does the official release of 1.4.1 give on the x9 lite?

**Comment by alexdibi** [comment]
@frozenskys 
Script Syntax Error
BF/radios.lua
incompatibile precompiled

**Comment by frozenskys** [comment]
I don't have an x9 lite available to test on but I just downloaded the 1.4.1 release and tried it in the simulator and it works fine - no need to add anything about x9lite in radios.lua. I suggest you delete any luac files off your SD card, and delete the current radios.lua on there as well, then try installing the 1.4.1 files again.

**Comment by alexdibi** [comment]
@frozenskys ok i Will try with another micro SD with only ad card contents for opentx 2.3.1 and lua 1.4.1

**Comment by frozenskys** [comment]
@alexdibi did you get it fixed?

**Comment by alexdibi** [comment]
@frozenskys yes there was some file put wrong in the sd ....
