### ISSUE TITLE
T16 Support

### ISSUE THREAD

**Issue by wingspinner** [betaflight/betaflight-tx-lua-scripts#272]
The BF dev team has announced support for the T16. Can you officially add it to these scripts? In the meantime I'll try the Horus version since the T16 is closes to Horus that any other Frsky models (I think!) I'll note any issues and either fix them or send back to you or both. Thanks!

**Comment by mikeller** [comment]
@wingspinner: The Jumper T16 is supported (#242), and there are no separate scripts for individual TX.

**Comment by tiaanv** [comment]
Jumper T16 Pro
BF script 1.4.1
OpenTX 2.3.2N27 nightly build
Multiprotocol module updated to latest with bootloader (FWIW)
the BF.lua script runs fine... can also page through various settings... but nothing has values.
Telemetry works fine.
BF script on my Taranis X7 with exact same quad worked fine...

I'm guessing this is not ready for primetime yet. Not sure if anyone has got it working yet.

**Comment by frozenskys** [comment]
@tiaanv when you say telemetry works fine how are you checking this (and what protocol are you using SPORT or CSRF?)  Also it might be worth logging this as an issue on the OpenTx github.

**Comment by tiaanv** [comment]
> @tiaanv when you say telemetry works fine how are you checking this (and what protocol are you using SPORT or CSRF?) Also it might be worth logging this as an issue on the OpenTx github.

SmartPort Telem
![image](https://user-images.githubusercontent.com/4703398/67574671-2d7feb80-f73b-11e9-91c2-1b09116a6c1f.png)
values form betaflight streaming to TX.

I will log it there as well.

**Comment by frozenskys** [comment]
@tiaanv Yup that looks good. I don't personally have a T16 to test on so I'll try and add some debug output to a build and ask you to run it if that's ok?

**Comment by tiaanv** [comment]
> @tiaanv Yup that looks good. I don't personally have a T16 to test on so I'll try and add some debug output to a build and ask you to run it if that's ok?

No problem. Happy to help.

**Comment by frozenskys** [comment]
I'm also assuming you don't get the flashing "No Telemetry" line at the bottom of the screen? (although I think the flashing is broken in the nightlies)

![No_Telem](https://user-images.githubusercontent.com/28024/67575988-97959200-f735-11e9-9e2b-3f928389274c.png)

**Comment by tiaanv** [comment]
No. I don't. Unless I remove the battery from the quad ;) Then of course it flashes.  So I guess it is in the latest nightly.

**Comment by tiaanv** [comment]
Hey @frozenskys 
Seems this is a known one.
https://github.com/opentx/opentx/issues/7005#issuecomment-546360511
Hang ten before further effort.

**Comment by 3djc** [comment]
Sorry guys, this can be closed. It is a multi/OpenTX long standing issue. Will be fixed through a combination of multi and OpenTX updates

**Comment by tiaanv** [comment]
Thx @3djc

**Comment by frozenskys** [comment]
@3djc thanks for the update - saves me disappearing down the telemetry rabbit hole 😃

**Comment by wingspinner** [comment]
Hmmm, Am i confused? When I downloaded the release version the only Jumper model shown in the radio selection is the T12

**Comment by wingspinner** [comment]
Ok, my apologies for wasting your time.  whatever I downloaded it must be wrong. Ill close this for now.

**Comment by mikeller** [comment]
@wingspinner: I think the fault is not on your side. What @3djc is stating in https://github.com/betaflight/betaflight-tx-lua-scripts/issues/272#issuecomment-546361510 is that the multiprotocol firmware and OpenTX are not ready yet to support bidirectional telemetry - if you'd be using a different RX module like XJT or Crossfire then the lua scripts would be working fine.
Keep following the latest OpenTX releases, there will be a mention when this is fixed for the multiprotocol module.
