### ISSUE TITLE
Clean OpenTX 2.3.1 w/BF 1.4.1 = "Attempt to call upvalue"...

### ISSUE THREAD

**Issue by leonard4** [betaflight/betaflight-tx-lua-scripts#282]
I haven't flown in a year and hadn't used BF Lua since I was getting plagued with the out of memory issue we had before. I'm starting clean on my radio and I just formatted my SD card on my X9D+, I flashed OpenTX 2.3.1 and extracted the latest SDCard contents to my sd card, and then extracted the latest BF 1.4.1 lua files with BF 4.1. I set the script to "bf" and restarted the radio. When I try to open the telem page I am presented with this:

![20191108_135553](https://user-images.githubusercontent.com/1154391/68515162-d565e080-0234-11ea-8550-e98cdfb6bb11.jpg)

It does this about 3-4 screens in right after the PID/Advanced page, I have my fw built with: noheli, and nooverridech. I haven't found any searches on open or closed issues and google is coming up empty. Any advice or ideas?

**Comment by leonard4** [comment]
I found that if I edit out x9pre.lua file and comment out the "filters.lua" page, then everything works correctly. Not sure if that helps identify the problem.

**Comment by mikeller** [comment]
@leonard4: What flight controller / firmware version are you using? A CLI `diff` of the firmware would help as well.

**Comment by leonard4** [comment]
Running a Bardwell F4 with BF 4.1.  I'm getting the same syntax error on two different quads, and even with no quads on, just trying to access the filter lua page itself.

**Comment by klutvott123** [comment]
I'm not able to reproduce this on my QX7 or in the sim. @leonard4 could you try deleting the .luac files and see if it gives you a more detailed error message?

**Comment by GarageTech** [comment]
I have the same problem, but i solved it by re-writing whole betaflight-tx-lua-scripts to SD card on PC.
Also important SAFELY remove SD card after writing. Problem in that files have wrong size during writing.

**Comment by klutvott123** [comment]
@GarageTech Could you tell us more about how you were able to reproduce this issue? Might be useful information.
