### ISSUE TITLE
Does not work with Open-TX 2.2 RC17

### ISSUE THREAD

**Issue by 8bitreid** [betaflight/betaflight-tx-lua-scripts#29]
when using this on RC17 I am not able to get or set values.

**Comment by stony2k** [comment]
Same problem here. Is it possible to downgrade the Taranis to RC16?

**Comment by 8bitreid** [comment]
You can select different RC's and load them accordingly.  However, the notes only say it doesn't work with RC11.  Does this mean everything after 10 does not work?

**Comment by stony2k** [comment]
As far as I can see, the problem isn't related to the Open-TX firmware. My
Taranis doesn't receive the telemetry data, which it did before. Maybe
there is some connection broken.

2017-05-22 17:52 GMT+02:00 Reid Mewborne <notifications@github.com>:
