### ISSUE TITLE
Saving ... Retrying

### ISSUE THREAD

**Issue by robertsberzins** [betaflight/betaflight-tx-lua-scripts#304]
Hello all,

I am currently experiencing problem that I can not save any changes in any settings using BF LUA script.
My be You could help or suggest something.

My setup:
1. Drone - Beta75 Pro 2 [Betaflight 4.1.2](SPI Frsky FCC (Built-in) https://betafpv.com/collections/pro-series/products/beta75-pro-2-brushless-whoop-quadcopter
2. VTX & Cam - A01 AIO Camera 5.8G
3. TX: Taranis X9D+ SE 2019 [OpenTX 2.3.4]
4. TX internal module: ISRM-S-X9 [1.1.0/1.1.3 FCC]
5. LUA script [1.4.1]

Observations:
1. See all settings PID, VTX, Rates, etc. using BF LUA script on X9D+
2. See all settings in OSD
3. Can change all settings PID, VTX, Rates, etc in OSD.
4. Telemetry working, can see: RSSI, VFAS, Curr, Tmp1, etc. in X9D+ Model Telemetry

Problem:
1. Can not save any settings using BF LUA script.
2. Screen show "Saving ..." and then "Retrying" after that loads old values that are not changed

**Comment by ss8688** [comment]
same problem with my mobula6
