### ISSUE TITLE
NO VTX with Betaflight 3.2

### ISSUE THREAD

**Issue by MaikFPV** [betaflight/betaflight-tx-lua-scripts#32]
Flashed Betaflight F3 Board with unreleased Firmware 3.2 and don´t get the VTX values. PIDs work perfectly.
With Betaflight Firmware 3.1.7 VTX and PIDs work.
Thanks for your help!!!

**Comment by digaus** [comment]
Have 3.2 on my F7, but an older version. Also check for tlm_inversion in CLI

**Comment by MaikFPV** [comment]
Flashed it again and did " Reset Telemetry" on my Taranis and it works perfectly!
