### ISSUE TITLE
[GPS Rescue] descent_dist vs min_dth

### ISSUE THREAD

**Issue by 0crap** [betaflight/betaflight-tx-lua-scripts#327]
The current LUA GPS section allows you to change the "gps_rescue_descent_dist" value.
I prefer to have the possibility to change the "gps_rescue_min_dth" value in this place.
Can that be changed?

Not only me, but also a few flying buddies got confused by this.
Which resulted in unwanted crashing of quads, during GPS Rescue testing.

**Comment by klutvott123** [comment]
I'm not sure we should replace `gps_rescue_descent_dist`, but we could have `gps_rescue_min_dth` in addition to it. It would have to be added to MSP first so it might be too late for 4.2

**Comment by mikeller** [comment]
@klutvott123: Yeah, that's something for 4.3.

**Comment by 0crap** [comment]
Too bad MSP needs an update, that's risky with 4.2 around the corner.
Hope it can be done in 4.3.
