### ISSUE TITLE
X9D + and - buttons swapped into Gyro/Motor tab

### ISSUE THREAD

**Issue by Mateyhv** [betaflight/betaflight-tx-lua-scripts#346]
Minor issue. + and - buttons act counterintuitive for 'Gyro Update' and 'PID Loop' inside the Gyro/Motor tab. - increases the number and + decreases the number.

Tested on Frsky X9D+, OpenTX 2.3.7, BF lua 1.3.5, BetaFlight 4.1.6

**Comment by klutvott123** [comment]
Yes, because the value we're changing is the denominator for pid/gyro rate, but I agree it's a little counterintuitive. Made a PR with a fix. Keep in mind that these parameters have been removed from the scripts for BF 4.2 and up, but they will still be there for earlier Betaflight versions.
