### ISSUE TITLE
[Feature Request] Add the BF slider values into the BF Lua script

### ISSUE THREAD

**Issue by RohanClegg** [betaflight/betaflight-tx-lua-scripts#355]
Sorry if i'm typing in the wrong place, couldn't find the feature requests bit.

It would be great if you could **add sliders into the BF Lua script**, so people slider tuning can do it on their radio, rather then needing to bring a laptop with them when they go out to fly.

You could put this in the PIDs section, and allow people to enter a value between 0 and 2 depending on what they want their sliders set at. 

It would be great to also have this idea in the filters section too for the Gyro and Dterm filter multipliers.

I think that this will be a great addition, as It will make tuning simpler and quicker to do, especially for the people who use sliders.

Thanks, 

Rohan

**Comment by klutvott123** [comment]
PR for simplified tuning is up https://github.com/betaflight/betaflight-tx-lua-scripts/pull/391. Test version included in PR if anyone wants to try it.
