### ISSUE TITLE
Telemetry page error

### ISSUE THREAD

**Issue by eaglerock86** [betaflight/betaflight-tx-lua-scripts#356]
Hi, im trying to run version 1.5.0 on my X-lite s, but when i hold page down i just get" Use TOOLS menu instead of this"
Any idea on what could be the problem ?
Thanks :)

**Comment by marekwiecek** [comment]
From:
https://github.com/betaflight/betaflight-tx-lua-scripts#installing

> Running the script as a telemetry page
> Due to issues with input mapping and memory overruns, running the script as a telemetry page is no longer supported. The only way to run the script is through the Tools screen in the OpenTX main menu.

Long Press Menu key on taranis and run Betaflight ...

**Comment by eaglerock86** [comment]
Thanks you, got it to work through the tools tab :)
