### ISSUE TITLE
I can see BF settings, but they don't change.

### ISSUE THREAD

**Issue by nullrnd** [betaflight/betaflight-tx-lua-scripts#359]
Hello!

I can see the PID and VTX settings, change the values, but they are not applied. The VTX configuration is changed through the BF configurator.

Jumper T12 (opentx 2.3.4), matek f405 ctr (BF 4.2)

**Comment by klutvott123** [comment]
Are you selecting "save settings" from the menu after changing the values?

**Comment by nullrnd** [comment]
No. Where can i find this menu?

**Comment by klutvott123** [comment]
Long press "enter" and it will pop up. Select "save settings" from the menu and press enter again.

**Comment by nullrnd** [comment]
Ok, thank you!!!
