### ISSUE TITLE
Horus X10S 

### ISSUE THREAD

**Issue by 4dimensio** [betaflight/betaflight-tx-lua-scripts#360]
Good afternoon,
 I have a Horus X10S running OpenTX 2.3.5 and trying to use BF lua 1.5.0. I go to System>Tools> and click Betaflight Setup which is number 9 in my tools menu and all that happens then on screen is " Betaflight initializing" that's it. I have even went into the "scripts" folder and clicked the scripts themselves whether it's PIDS,vTX lua scripts and nothing. The screen will flash and that's it. Am I missing something or do I need to use a lower BF lua scripts like 1.4.1?

Thank you for your time

UPDATE.....
Well for some reason I can not get either BF lua scripts 1.4.1 or 1.5.0 to work with CRSFshot v2.3.5  of OpenTX. It doesn't matter if I try my X9D or my Horus X10S. I can watch the scripts compile when I click "Betaflgith setup" in the tools menu and then go back to my tools menu and click BetaFlight setup and it just sits there stating on either of my RC's "Betaflight initializing", that's it. Whats the issue?

**Comment by klutvott123** [comment]
Don't you need the TBS nightly build of OpenTX to use CRSFshot?

**Comment by 4dimensio** [comment]
My issue has been already addressed,thank you for answering back.
 The post can be closed.
