### ISSUE TITLE
[Feature Request] Failsafe Settings

### ISSUE THREAD

**Issue by TomAlperin** [betaflight/betaflight-tx-lua-scripts#388]
Would it be possible to add the ability to change the failsafe setting. Currently most GPS return to home settings can be edited but it doesn’t look like the failsafe can be switched between drop and GPS rescue for situations where it is not practical to use GPS rescue.

**Comment by klutvott123** [comment]
@TomAlperin I just made a PR adding a failsafe page https://github.com/betaflight/betaflight-tx-lua-scripts/pull/390. A test version is included in the PR. Feel free to try it if you want.

**Comment by TomAlperin** [comment]
Tested on two transmitters, an X-Lite Pro and Horus X10s. Works correctly on both. Thanks for doing this so quickly.
