### ISSUE TITLE
"Syntax Error" when launching betaflight tools on OpenTX 2.3.14 Jumper T-Lite

### ISSUE THREAD

**Issue by DavidJJ** [betaflight/betaflight-tx-lua-scripts#404]
## Betaflight Lua scripts fail to launch on OpenTX 2.3.14 on Jumper T-Lite transmitter ##

1. Install Open TX 2.3.14 (or 15 preview)
    1. Install Betaflight Lua Scripts onto SD card along with rest of OpenTX sd card content
    1. Reboot transmitter
    1. Open tools menu
    1. Choose Betaflight
       - (compiles without error)
    1. Re-Choose Betaflight tools
    1. Result: "Syntax Error"
2. Provide as much information as possible about your hardware and software, including:
- OpenTx 2.3.14 release,  
- Jumper T-lite transmitter (version 1)
- Betaflight Lua 1.5.0

**Comment by DavidJJ** [comment]
I'm trying to get this working using a NewBeeDrone AcroBee V3.  I have it set to FrSky D8 protocol. 

At first I was trying to get into the menu itself without a drone turned on or plugged in.  But I just tried now with my AcroBee turned on and it still "syntax error" out as soon as I click the betaflight menu.

**Comment by klutvott123** [comment]
D8 is the issue. It should have given you the "Telemetry protocol not supported!" error message, but it was broken in opentx 2.3.12 and that's why you're only getting "Syntax error" without any additional information

**Comment by DavidJJ** [comment]
With no reciever powered on what would / should it say?  

Also thank you for your help.

**Comment by klutvott123** [comment]
With no receiver powered on it will say "Initialising" for 1.5.0. For 1.6.0 the message has been changed to "Waiting for connection". It has to be connected so that the scripts can detect which Betaflight version you're using.
Frsky D16 with Smartport telemetry or crossfire is needed for the scripts to be able to communicate with the flight controller

**Comment by DavidJJ** [comment]
I switched over to D16 and I now get past the initial screen and to "downloading VTX Tables" but nothing after that even after multiple minutes.   

I'm trying to find documentation on what the receiver in the AcroBee actually supports (this is my only frsky receiver) to find out if it has smartport or not.

**Comment by klutvott123** [comment]
If you got past the "Initialising" stage it means that communication is working and it probably supports smartport telemetry.
Downloading vtx tables usually takes a while, but several minutes seems a little excessive.
