### ISSUE TITLE
incomplete board information prevents further work

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-tx-lua-scripts#411]
@klutvott123 During a test on a MatekH743 i noticed that the first run of the scripts after downloading the boardinfo fails.
After looking at the generated file, i noticed that an entry in the `manufacturer_id` is empty and that it breaks the first run of the scripts. 
After entering `manufacturer_id MTKS` in the cli and restarting the script everything runs without problems.

imo should break this on all other legacy target as well.
pls can you check this ?!

**Comment by klutvott123** [comment]
Fixed in https://github.com/betaflight/betaflight-tx-lua-scripts/pull/412. Test version included in PR. 
This should have been able to handle empty strings, but wasn't because I forgot to wrap them in "" when writing to file. 
Thanks for testing and reporting this 👍
