### ISSUE TITLE
Support for slider tuning

### ISSUE THREAD

**Issue by jasc76** [betaflight/betaflight-tx-lua-scripts#414]
Will there be a version with slider support (BF4.3)

**Comment by haslinghuis** [comment]
Please take a look: https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20211220.5042

**Comment by ElRouge** [comment]
I tried but it gets stuck on "downloading board info" did I do something wrong?  with bf 4.2 and the "official" lua worked
![16418331058157844808025908307080](https://user-images.githubusercontent.com/96788158/148804253-08997381-f583-4e82-9ef6-e7088d410a0b.jpg)

**Comment by klutvott123** [comment]
Which rx system are you using?

**Comment by ElRouge** [comment]
> Which rx system are you using?

Elrs 868

**Comment by klutvott123** [comment]
update to version 2.0.1

**Comment by ElRouge** [comment]
No 1.2.1

**Comment by klutvott123** [comment]
Then it won't work. at least 2.0.1 is required for it to work

**Comment by ElRouge** [comment]
> Then it won't work. at least 2.0.1 is required for it to work

Ah ok i upgrade It ;-)
