### ISSUE TITLE
Stuck at "Downloading board info" message on some boards.

### ISSUE THREAD

**Issue by ase-dcexpert** [betaflight/betaflight-tx-lua-scripts#416]
I installed the BF 4.3.0 RC1 using Configurator 1.8.0 RC1 on two of my quads (pink and grey CineRace 20). Both quads use the same ELRS receiver but different FC boards (pink: CRAZYBEEF4FR, grey: GEPRCF411).

The BF telemetry sensors show up fine in my Taranis for both quads, so telemetry is working for both!

On my Taranis X-Lite S I installed the latest nightly build of the LUA script:
https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20211223.5115

The LUA script works fine with the pink quad and stuck at the grey quad during initialization with the message "Downloading board info".

I attached the "diff all" output from both quads. Maybe you can figure out why the grey quad is not initializing the LUA script and stuck with "Downloading board info".
[BTFL_cli_Grey_CineRace_4.3.0.RC1_LUA_NOK.txt](https://github.com/betaflight/betaflight-tx-lua-scripts/files/7784326/BTFL_cli_Grey_CineRace_4.3.0.RC1_LUA_NOK.txt)
[BTFL_cli_Pink_Cinerace_4.3.0.RC1_LUA_OK.txt](https://github.com/betaflight/betaflight-tx-lua-scripts/files/7784327/BTFL_cli_Pink_Cinerace_4.3.0.RC1_LUA_OK.txt)

**Comment by klutvott123** [comment]
Looks like telemetry isn't enabled

**Comment by ase-dcexpert** [comment]
UPDATE:
I have a third quad running BF 4.3.0 RC1 (URUAVHD85) with the same board (CRAZYBEEF4FR) like the pink (LUA working) quad.. this URUAV is also stuck at "downloading board info"

Telemetry is activated on all three quads!

CLI diff all attached
[BTFL_cli_URUAV_85HD_4.3.0.RC1_LUA_NOK.txt](https://github.com/betaflight/betaflight-tx-lua-scripts/files/7784449/BTFL_cli_URUAV_85HD_4.3.0.RC1_LUA_NOK.txt)
d

**Comment by klutvott123** [comment]
are you using expresslrs 2.0.1?

**Comment by ase-dcexpert** [comment]
Thats the difference.. only the pink CineRace had the 2.0.1 ELRS flashed.. the others had 2.0.0!

I just flashed ELRS 2.0.1 and now it is also working with the other quad! Thanks! I did not notice, that such a small difference causing the LUA to stuck!
