### ISSUE TITLE
Horus Lua script get no telemetry

### ISSUE THREAD

**Issue by sniperxnl** [betaflight/betaflight-tx-lua-scripts#42]
Guys,

I have the latest OpenTX on my horus
I use Crossfire with latest firmware and micro RX
My FC is a Fortini F4, i get in my sensor tab on the horus my Voltage, Mah and current.
But when i open the HORUS.LUA it say NO TELEMTRY

**Comment by raphaelcoeffic** [comment]
@sniperxnl the old code was not supporting crossfire, but the refactored code we checked in yesterday does. That should work for you now.
