### ISSUE TITLE
CMS functionality via Lua BF don't work - BF 4.3.0 RC2

### ISSUE THREAD

**Issue by Martivip** [betaflight/betaflight-tx-lua-scripts#422]
CMS functionality via Lua BF don't work, on my Taranis X9D+ 2019 SE I only see blank screen.

After launch the latest BF nightly Lua Script (Betaflight CMS) I do not see any menus only the blank screen, under the upper right corner there is Refresh information with + sign but pusching any button don't refresh at all.
 
My configuration:
Taranis X9D+ 2019 SE with 2.3.14 OpenTX
Latest BF Nightly LUA script v20211229.5241
TX Namimo Flash OLED with 2.0.1 ELRS
Integrated RX in AIO Board, target: BETAFPVF4SX1280 with installed BF 4.3.0 RC2

![IMG_1513](https://user-images.githubusercontent.com/72009313/148986587-353e5b32-d758-46ff-b1d5-7b33950633c0.JPG)
![IMG_1512](https://user-images.githubusercontent.com/72009313/148986633-573646bc-62e7-4ae1-b733-6398ed1f2238.JPG)

**Comment by klutvott123** [comment]
The cms script only works with TBS crossfire/tracer at the moment

**Comment by Martivip** [comment]
@klutvott123 ok thanks for the information
