### ISSUE TITLE
Feature request: Support for Ghost telemetry

### ISSUE THREAD

**Issue by mavenius** [betaflight/betaflight-tx-lua-scripts#443]
For as much detail as I can think of, I'm using a RadioMaster TX16S with EdgeTX 2.7.1 and the Ghost protocol (BF 4.3 stable release.)

When I open either Betaflight CMS or Betaflight setup (for script versions 1.6.0 each,) I am presented with "Telemetry protocol not supported!"

Looking at the readme for this repo, I see that Ghost isn't listed as a supported protocol; if that's incorrect and I'm doing something else wrong, then I'm sorry for the trouble :-) 

Thanks!

**Comment by daleckystepan** [comment]
Hi man,
it is on the way:
- https://github.com/betaflight/betaflight-tx-lua-scripts/pull/419
- https://github.com/betaflight/betaflight/pull/11242
- https://github.com/EdgeTX/edgetx/pull/1377

and new Ghost FW.

**Comment by mavenius** [comment]
@daleckystepan Excellent; thank you for the hard work!

**Comment by larry415** [comment]
https://github.com/betaflight/betaflight-tx-lua-scripts/issues/443#
