### ISSUE TITLE
jumper t16/ betaflight lua installs, but when I run it with eachine uz65 on, it says "waiting on API" and stay's on that message. Telemetry is on in Betaflight and the sensors show up in edge tx on radio. What am I missing?

### ISSUE THREAD

**Issue by ronbon172** [betaflight/betaflight-tx-lua-scripts#464]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by ronbon172** [comment]
what missing info do you need?

**Comment by haslinghuis** [comment]
Consider joining Discord please.

**Comment by ronbon172** [comment]
i am a member of discord

**Comment by haslinghuis** [comment]
Use latest LUA here: https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases

**Comment by haslinghuis** [comment]
Missing info is about firmware on flight controller, radio and receiver (see opening message of this PR)

**Comment by ronbon172** [comment]
FC firmwarte: betaflight Crazybeef4fr 4.4.0-rc1
Radio: Jumper t16
Radio firmware: Edgetx "Flying Dutchman" v2.8.0
reciever: Onboard Frsky SPI D8 receiver Version

**Comment by klutvott123** [comment]
frsky SPI D8 is the issue. try D16 if possible.

**Comment by ronbon172** [comment]
that worked...thanks :-)
