### ISSUE TITLE
Problema su Radio BetaFpv Lite 3 PRO

### ISSUE THREAD

**Issue by SimonTinyFPV** [betaflight/betaflight-tx-lua-scripts#469]
copio i file nella directory come spiegato installo il BF Lua ma poi non riesco ad impostare la visualizzazione Script perche mi dice che non esiste il file nella SD

**Comment by klutvott123** [comment]
english please. are you launching the script from the tools menu? which file does not exist?

**Comment by SimonTinyFPV** [comment]
copy the file in the directory as explained install the BF Lua without risk to set the display Script because I say that the file does not exist in the SD

**Comment by SimonTinyFPV** [comment]
copy the file in the directory as explained install the BF Lua without risk to set the display Script because I say that the file does not exist in the SD

**Comment by SimonTinyFPV** [comment]
https://user-images.githubusercontent.com/124176978/216118103-6a607088-977c-4b69-b2b1-2e3e7db966d9.mp4

![Immagine WhatsApp 2023-02-01 ore 18 26 3](https://user-images.githubusercontent.com/124176978/216118110-dcb2b1b9-b5cd-4440-b094-f86c5820e8ab.jpg)
![Immagine WhatsApp 2023-02-01 ore 18 26 33](https://user-images.githubusercontent.com/124176978/216118112-7e9d60bd-0271-43e0-9c96-ea8bce65d80d.jpg)
![Immagine WhatsApp 2023-02-01 ore 18 26 34](https://user-images.githubusercontent.com/124176978/216118113-2a6c930a-7cd2-42f1-824e-712c66e4b3bb.jpg)
![Immagine WhatsApp 2023-02-01 ore 18 26 35](https://user-images.githubusercontent.com/124176978/216118116-0456f9ea-c7dc-4579-b4c9-a7e9dc5c3766.jpg)

**Comment by SimonTinyFPV** [comment]
when I am in the Display category that I have to enable the LUA to see the PIDs on the radio display it tells me that the script is not present in the SD this problem does it with all versions on this radio

**Comment by klutvott123** [comment]
Looks like you did everything right. to start and use the script, you have to select "Betaflight setup" from the TOOLS menu. There is no telemetry script anymore, so you don't have to do anything in the DISPLAY page 🙂

**Comment by SimonTinyFPV** [comment]
ok thanks  I'll let you know tomorrow

**Comment by SimonTinyFPV** [comment]
![Uploading 697703EC-8C08-47D1-9099-506B84EAE1CB.jpeg…]()

**Comment by SimonTinyFPV** [comment]
No work 
![673C2809-7519-4EF9-B7EA-69C15F84CBEE](https://user-images.githubusercontent.com/124176978/216282993-b7ffe418-329c-4ae0-ae9d-07c5178b7952.jpeg)

**Comment by klutvott123** [comment]
Is telemetry enabled in betaflight?

**Comment by SimonTinyFPV** [comment]
Ok NOW work thanks @klutvott123 💪
![2FB26754-4E81-406B-BA5E-C3379D91520B](https://user-images.githubusercontent.com/124176978/216292634-be199aec-cef5-4b1b-982a-18372f4de49c.jpeg)

**Comment by klutvott123** [comment]
Awesome! 😁
