### ISSUE TITLE
Waiting for VTX Tables

### ISSUE THREAD

**Issue by TomAlperin** [betaflight/betaflight-tx-lua-scripts#474]
1. Describe your problem;
Script sticks on waiting for VTX tables on digital video builds.

2. Include ways to reproduce the problem;
Connect to a quad that is using a digital VTX and does not have VTX tables set up. This may also be related to the BetaFlight 4.4 option to not build with the analog video option so would be best to test on a firmware that is not build with this.

3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
I am using the latest version of EdgeTX. Most boards were either the Succex-D F7 or the JB F7 v2.

- the version of all the software used;
BetaFlight 4.4 build for use with HD video system. EdgeTX "Flying Dutchman" v2.8.1. This issue occurs with CrossFire or ExpressLRS and I do not believe it's related to the link.

The issue appears to be that VTX tables can not be downloaded because they do not exist or that there is a communication issue due to the flight controller not having the VTX code. The work around I have found is to get MCU_IDs for all of the models that I have that use digital and making copies of one of the analog VTX files with names matching all of the ids.

A possibile solution would be to detect digital setups and skip fetching the VTX tables. A similar VTX file could be saved that would remove the VTX menu for that craft since it is not usable for digital VTX units.

**Comment by klutvott123** [comment]
@TomAlperin https://github.com/betaflight/betaflight-tx-lua-scripts/pull/475 should fix it. There's a zip file for testing there too if you want to try it. This will bypass the vtx tables download if the firmware has been compiled without the VTX option.
