### ISSUE TITLE
Lua script hang on waiting for vtx

### ISSUE THREAD

**Issue by Pancronos** [betaflight/betaflight-tx-lua-scripts#476]
I upgraded to 4.4.1 firmware on a diatone F740 AIO and removed led strip and vtx (have a caddx vista) in other options, when launching betaflight setup on RM-TX16s (latest lua downloaded yesterday) it hangs on vtx table. I thought it was going to timeout after the check for vtx and get all the menu, but it hangs on vtx table even after 30 seconds. Tried several times.
I saw a commit [Create empty vtx table if not available](https://github.com/betaflight/betaflight-tx-lua-scripts/commit/61d302980967f05f3e8a4957dfc45c859559cdf0) but this doesn't seem to work.
Flashed the firmware with vtx table and LUA script works fine.

**Comment by Pancronos** [comment]
saw previous issue 
https://github.com/betaflight/betaflight-tx-lua-scripts/issues/470#top

**Comment by klutvott123** [comment]
try a nightly build https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases
