### ISSUE TITLE
Waiting for Api

### ISSUE THREAD

**Issue by druckgott** [betaflight/betaflight-tx-lua-scripts#477]
#System
Taranis X-Lite Pro
Expresslrs 3.2.1
Betaflight 4.4.1
Current Version of this Script

on FrSky it worked, but Today I switch to Expresslrs.

## If you believe there is an issue with the firmware itself please follow these steps:
I have "Waiting for Api" if I go to the script
I have Expresslrs 3.2.1 with 400 baud rate
I have installed Smartport 

Checkt all in this Topic: https://github.com/betaflight/betaflight-tx-lua-scripts/issues/470

Hopfully I did not lost anything

**Comment by klutvott123** [comment]
Make sure telemetry is still enabled in the receiver tab

**Comment by druckgott** [comment]
Yes it's enabled I checkt it several times

**Comment by haslinghuis** [comment]
Expresslrs does not provide smartport it uses the crsf protocol

**Comment by druckgott** [comment]
Ok this I did I ly reinstall after I'd did not work with crsf Protokoll. But what could be case this issue? Can I see any log?

**Comment by klutvott123** [comment]
is rx and telemetry working? the issue is that the script isn't getting a response to the request.

**Comment by druckgott** [comment]
Yes that's the Stange point telemetry is working an rx is also working

**Comment by haslinghuis** [comment]
Just installed nightly build on MERCURYG4 with ELRS 3.2.1 and `Betaflight setup` script seems to be fine.
But using `Betaflight CMS` I get only the main screen and no movement.

I have no VTX installed.
@druckgott what VTX setup do you have?

**Comment by druckgott** [comment]
Betaflight I have compiled it, but I have nothing inside:
![grafik](https://user-images.githubusercontent.com/18383738/235339415-24e043e8-e5c8-4919-92db-290022689454.png)

Is there a way to deaktivate it temporary (comment out) to check if this is the problem

I have DJI VTX

**Comment by druckgott** [comment]
Ko I sed Baudrate to 3.75M and now it works ;-)

**Comment by klutvott123** [comment]
lol that's strange. It has always worked for me at 400k. you have to use bf master if you want betaflight cms to work

**Comment by druckgott** [comment]
Ah ok no it's not so Important, I only test it because you mentioned it
