### ISSUE TITLE
Fix for ''stuck on downloading VTX tables''

### ISSUE THREAD

**Issue by Hillbilly-Phil** [betaflight/betaflight-tx-lua-scripts#478]
If you deselect ''VTX'' when building your cloud BF firmware, then the BF Lua script will be stuck when trying to download the VTX tables. 

Maybe the Lua script could be updated to work with cloud builds without ''VTX''?

My workaround to use the BF Lua Script was to Backup my current BF Firmware, flash the same version just with ''VTX'' selected and load the backup.

Many Thanks

**Comment by klutvott123** [comment]
try this https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20230313.7

**Comment by mituritsyn** [comment]
> try this https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20230313.7

hi, this works for me, but I have this issue in latest release version
https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20231019.9

**Comment by haslinghuis** [comment]
@atomgomba please have a look

@mituritsyn please provide support ID and an indication when the error occurs.

**Comment by atomgomba** [comment]
I just tested [v20231019.9](https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases/tag/v20231019.9). I use TBS Sixty9 connected through CRSF  so "VTX" feature is not compiled in my firmware and hence no VTX table configured either. The radio used was a Tango 2. I deleted the dummy VTX table (lua file) from the SD card to force the script to try and download the VTX tables again. The result is that the Betaflight setup script works normally. We need more info to reproduce this.

**Comment by mituritsyn** [comment]
> @atomgomba please have a look
> 
> @mituritsyn please provide support ID and an indication when the error occurs.

sorry, missed message
still reproduced. indication is "downloading vtx tables"
Id: "86080f48-f149-48ca-9c5e-b2f1a8ad25af

**Comment by haslinghuis** [comment]
@mituritsyn please remove SCRIPTS/BF/VTX_TABLES/vtx_defaults.lua from SDC.
