### ISSUE TITLE
LiteRadio 3 Pro - Syntax Error

### ISSUE THREAD

**Issue by odixxx** [betaflight/betaflight-tx-lua-scripts#481]
when running the Betaflight Setup script - Syntax Error
![20230627_100823](https://github.com/betaflight/betaflight-tx-lua-scripts/assets/12283233/be2e546d-6efd-4a5f-80d5-87a3025a2283)

My setup:
Betaflight TX Lua Scripts 1.7.0
Betaflight 4.4.2
EdgeTX  v2.8.4

ps. on another radio X9D Plus everything works fine!

**Comment by klutvott123** [comment]
it means it didn't find "scripts.lua". Did you download a zip file from here https://github.com/betaflight/betaflight-tx-lua-scripts/releases ?

**Comment by Hofi** [comment]
I have the same error on a radiomaster zorro. I used the files from Release page.
![IMAG1443](https://github.com/betaflight/betaflight-tx-lua-scripts/assets/3236861/f6353e58-81ce-4356-a2bd-fdae5346e710)

**Comment by klutvott123** [comment]
Can you check if /SCRIPTS/BF/COMPILE/scripts.lua actually exists on your SD card? Would be strange if it's not there.
this https://github.com/betaflight/betaflight-tx-lua-scripts/releases/download/1.7.0/betaflight-tx-lua-scripts_1.7.0.zip is the file with the compiled scripts

**Comment by Hofi** [comment]
yes, it's there. i tried to copy the files multible times. I even tried reformatting the sd card.
![grafik](https://github.com/betaflight/betaflight-tx-lua-scripts/assets/3236861/15ff2e8d-bef9-48e3-93f9-6d7abce6756c)

**Comment by Hofi** [comment]
I found the issue. I tried another sd card from sandisk and it works. I guess the sd card that sipped with the radio is garbage ...

**Comment by raqso** [comment]
> when running the Betaflight Setup script - Syntax Error ![20230627_100823](https://user-images.githubusercontent.com/12283233/249070238-be2e546d-6efd-4a5f-80d5-87a3025a2283.jpg)
> 
> My setup: Betaflight TX Lua Scripts 1.7.0 Betaflight 4.4.2 EdgeTX v2.8.4
> 
> ps. on another radio X9D Plus everything works fine!

I wonder if you @odixxx  somehow managed to make this work on lr3 pro?

**Comment by albka1986** [comment]
I also have the same issue, even though the files are present. 
Device: Readiomaster Boxer.

**Comment by Hofi** [comment]
Have you tried another SD card? The SD card that came with the radio didn't work well for me. After changing SD card and copying files it should work.
