### ISSUE TITLE
Make VTX Tables optional for digital video systems (no VTX option for firmware cloud build)

### ISSUE THREAD

**Issue by starlino** [betaflight/betaflight-tx-lua-scripts#482]
Problem: lua script getting stuck at  "Downloading VTX Tables"

To reproduce
Compile 4.4.2 Firmware without VTX and  OSD(SD) option. Note the above problem

To fix: 
Compile 4.4.2 Firmware with VTX and  OSD(SD) option. Note the problem is fixed.

VTX tables are no longer needed for Digital HD  systems (ex DJI), so just make them optional.

**Comment by Maxatma** [comment]
Have same issue, for whatever reason, stuck on a Downloading VTX Tables. I don't even need them, but...
Maybe the script isn't working yet. Gonna check it again in a few years.
