### ISSUE TITLE
Readme.md - issue

### ISSUE THREAD

**Issue by adarkthinline** [betaflight/betaflight-tx-lua-scripts#483]
ISSUE:
Baud rate - Set to 400K in EdgeTX/OpenTX for Crossfire, Tracer, ExpressLRS and Ghost.

The above sentence should not include... "and Ghost." as part of the above statement.

I have GHST = Ghost protocol.
In my RadioMaster TX16s with EdgeTX 2.7.1 and in my FrSky Taranis X9D+ SE with OpenTX 2.3.15 there is NOT an option to set the Baud rate to 400K for GHST. Both the CRSF versions do and ELRS, but NOT GHST.

I think that this needs to be corrected for future reference.

Thanks

**Comment by haslinghuis** [comment]
https://github.com/EdgeTX/edgetx/discussions/1941

**Comment by haslinghuis** [comment]
https://youtu.be/2MwEoG-3k-A

**Comment by haslinghuis** [comment]
Resolved in #485
