### ISSUE TITLE
Radiomaster Boxer EdgeTX 2.9.1 - Error on script compilation

### ISSUE THREAD

**Issue by marcinczeczko** [betaflight/betaflight-tx-lua-scripts#489]
1. Problem description
On a brand new Radiomaster Boxer with internal ELRS with Edge TX 2.9.1 i installed BF Lua by copying to SDcard. Once I start script, I'm getting compilation error: "Syntax error, scripts.lua, "bt") error a" File not found

2. Ways to reproduce
- Radiomaster Boxer with ELRS
- EdgeTX 2.9.1.
- Install BF Lua
- Try to run BF Lua

Attached recording of what's actually happening

https://github.com/betaflight/betaflight-tx-lua-scripts/assets/4218395/fd8e743c-d9ea-42eb-bf7e-12ce00b32412

**Comment by klutvott123** [comment]
Please try another sd card

**Comment by marcinczeczko** [comment]
@klutvott123 thanks ! I replaced sd card and now it compiles just fine. Looks like the sd card that came together with radio is not a good quality one :(
