### ISSUE TITLE
"Cannot open" Error

### ISSUE THREAD

**Issue by alphat5** [betaflight/betaflight-tx-lua-scripts#49]
Hi, I just  intalled the script on my taranis X9D+ wich is running on "OpenTx  X9D+ - 2.2.0 (85863358) RC18". When I execute X9.lua, I receive the following error; 
`Script syntax error 
*followed by the path of the location of the script* 
cannot open`.

Does someone have an idea of this issue ?

Best regards,
Keone

**Comment by raphaelcoeffic** [comment]
@alphat5 we are using a complete new refactored code now, please have a look at it first.
