### ISSUE TITLE
Cannot change VTX settings

### ISSUE THREAD

**Issue by RCAviation** [betaflight/betaflight-tx-lua-scripts#508]
Hi! I'm really new to the FPV hobby but I hope someone is willing to help me out.

I'm running latest BF and have a TBS Unify32HV vtx set up for smart audio. Via goggles and sticks I can change band and power on my VTx.Also in BF on laptop VTX is turning green when battery is plugged in. But not through BF lua nor TBS lite Lua. What am I doing wrong? In BF Lua I cannot see or select more then Channel A,Power LV1. Through TBs Lite Lua I can select channels I want but they only change on my goggles OSD and not on output of my VTX. I'm out of options. 

Greetz from the Neterlands

**Comment by haslinghuis** [comment]
Hoi - ga naar https://discord.betaflight.com/invite for support.
