### ISSUE TITLE
JUMPER T15

### ISSUE THREAD

**Issue by SimoneDallaC** [betaflight/betaflight-tx-lua-scripts#511]
Lua does not work with the Jumper T15 resolution. Is there a way to fix it or have info to adapt it?

**Comment by haslinghuis** [comment]
Not sure. Resolution is already supported

https://github.com/betaflight/betaflight-tx-lua-scripts/blob/1a9002439c9105c9063f1431f354043e655f9cff/src/SCRIPTS/BF/radios.lua#L112

**Comment by pfeerick** [comment]
Just to clarify that... support for that resolution was added about five months ago, but the last *tagged* release for the Lua is from two years ago -1.7.0 - hence the need to use a nightly package to get that.
