### ISSUE TITLE
Display VTX frequency

### ISSUE THREAD

**Issue by si618** [betaflight/betaflight-tx-lua-scripts#6]
Would be nice to show vtx frequency for the current band and channel.

Frequencies are listed in manuals for [Tramp](http://www.immersionrc.com/fpv-products/tramp-hv-5-8ghz-video-transmitter/) and [TBS Unify](http://www.team-blacksheep.com/products/prod:unify_pro_hv).

**Comment by nitbeat** [comment]
Nice one 👍 
In the OSD I think its already visible right ?

**Comment by raphaelcoeffic** [comment]
Yes, it's really no problem. I'll do it the next days.

**Comment by raphaelcoeffic** [comment]
implemented in #11.

**Comment by raphaelcoeffic** [comment]
see https://github.com/betaflight/betaflight-tx-lua-scripts/releases/tag/v0.1
