### ISSUE TITLE
Horus X12S via Crossfire not saving values

### ISSUE THREAD

**Issue by Sniks6** [betaflight/betaflight-tx-lua-scripts#84]
Hi there,

my Horus X12S with the big Crossfire TX doesn't save the values (e.g. PIDs) to the Betaflight.

Here is my setup: 

- Horus X12S
- OpenTX-x12s-2.2.0 (Date 30.05.2017)
- Big Crossfire TX / Crossfire micro RX v2
- Crossfire 2.11 Firmware
- Betaflight 3.2.1
- LUA Script from 16.11.2017 10.00am

*Here is a video about this behaviour: [YouTube - Video](https://youtu.be/zIKZDqLEyIU)*

Perhaps you could give me a hint.

Thanks,

Alex

**Comment by codecae** [comment]
@Sniks6  Try using Betaflight 3.2.2.

**Comment by codecae** [comment]
No problem!  Glad I could help :)
