### ISSUE TITLE
Not value shown in lua script screen on XD9

### ISSUE THREAD

**Issue by fastfred529** [betaflight/betaflight-tx-lua-scripts#86]
Have a Omnibus F3 aio, FrSky XSR, ewrf vtx with smart audio, and configured in BetaFlight correctly. Telemetry sensors are updating constantly. Can adjust pids and vtx in the osd screen with the gimbals. No values on the bf lua script screen on my Taranis. Lost at what to try next.

**Comment by SkeemoFPV** [comment]
Same here, have had to go back to the last ‘revised’ version and all is ok again

**Comment by mikeller** [comment]
Can you please state what version of the scripts you are using?

**Comment by fastfred529** [comment]
Flashed the FrSky XSR receiver with the new firmware from the FrSky website. Working fine now. Not using the latest lua script.
