### ISSUE TITLE
Background task work without telemetry?

### ISSUE THREAD

**Issue by brycedjohnson** [betaflight/betaflight-tx-lua-scripts#99]
Looks like it should be possible to send time (and maybe some other stuff in the future) if there is no telemetry such as a frsky xm+.  Any problem with sending that data periodically?

**Comment by codecae** [comment]
Telemetry is required in order to send data other than rc frames to the flight controller

**Comment by brycedjohnson** [comment]
Dang!  Got a couple xm+ on some 2 inch quads and wanted to check out the time sent over msp, but i'll have to grab the bigger quads with XSRs.  Thanks for the quick response!
